"""add no_rek to Employee

Revision ID: 04716cbed9d6
Revises: 73ea04d0f1ad
Create Date: 2025-08-30 20:09:21.256256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04716cbed9d6'
down_revision = '73ea04d0f1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_rek', sa.String(length=50), nullable=True))

    with op.batch_alter_table('payroll_loan', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_loan', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('no_rek')

    # ### end Alembic commands ###
