"""Initial migration

Revision ID: 24eef6c79edb
Revises: 
Create Date: 2025-03-11 16:40:38.295799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24eef6c79edb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tenor', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('installment', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('installments_paid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pay_period', sa.String(length=7), nullable=True),
    sa.Column('gaji_pokok', sa.Float(), nullable=True),
    sa.Column('bpjs_ketenagakerjaan', sa.Float(), nullable=True),
    sa.Column('tunjangan_makan', sa.Float(), nullable=True),
    sa.Column('tunjangan_transport', sa.Float(), nullable=True),
    sa.Column('tunjangan_lainnya', sa.Float(), nullable=True),
    sa.Column('potongan_gaji', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Integer(), nullable=True),
    sa.Column('hutang', sa.Float(), nullable=True),
    sa.Column('upah_lembur', sa.Float(), nullable=True),
    sa.Column('thr', sa.Float(), nullable=True),
    sa.Column('loan_deduction', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['payroll_id'], ['payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_loan')
    op.drop_table('payment')
    op.drop_table('payroll')
    op.drop_table('loan')
    op.drop_table('user')
    op.drop_table('employee')
    # ### end Alembic commands ###
